title: The Typog Blog
description: A blog focused on analysing typography in sports.
header_text: Typography in Sports
footer_text: Copyright 2020 Joshua Nair
header_feature_image: ../uploads/ucl-night-old-trafford.jpg
bannerheight: 20vmax
logo: ../uploads/website-logo-new-3.png
favicon: ../uploads/favicon.ico
gridlayout: true
fixednavbar: false
upzoom: true
items:
  - siteurl: /aboutme
    name: Who Am I?
